DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Opiskelija CASCADE;
DROP TABLE IF EXISTS Opettaja CASCADE;
DROP TABLE IF EXISTS Yllapitaja CASCADE;
DROP TABLE IF EXISTS Aihe CASCADE;
DROP TABLE IF EXISTS Suoritus CASCADE;
DROP TABLE IF EXISTS Suorittaja CASCADE;